# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372597df2e518939d062c4081c5b307b12e116774d1981cc62e126f97cd687775b55458ff074868c8b534bafe587f1cc18fe0745eecce8ee27837bbf2c7b8678

test:
  secret_key_base: 076fc0ac4fc9700a508ecc10290e6c88fcb0d6bc81f9a5bf0a3dfdcaeba05225876f62a1727157ca322aeae08ced095a8d129c4d89928575e2327983410d0993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
